---
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html#authorized-key-adds-or-removes-an-ssh-authorized-key
- name: Deploy ssh-keys to remote host
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
    state: present
  with_items: ssh_users
